export const data=[
    {name:'Laptop',category:"electronics",description:'a great Laptop',price:50},
    {name:'Phone',category:"electronics",description:'a great Phone',price:5},
    {name:'Ipad',category:"electronics",description:'a great ipad',price:90},
    {name:'Washing Machine',category:"electronics",description:'a great washing Machine',price:20},
    {name:'onions',category:"groceries",description:'fresh onions',price:2},
    {name:'potato',category:"groceries",description:'fresh onions',price:5},
    {name:'tomato',category:"groceries",description:'fresh onions',price:3},
    {name:'asparagus',category:"groceries",description:'fresh onions',price:11},
    {name:'eye shadow',category:"cosmetics",description:'Good, eye shadow',price:5},
    {name:'Liner',category:"cosmetics",description:'Good, Liner',price:5},
    {name:'Fair and Lovely',category:"cosmetics",description:'Good, Fair and Lovely',price:5},
    {name:'Body Lotion',category:"cosmetics",description:'Good, Body Lotion',price:5},
    {name:'Shirt',category:"clothes",description:'Soft and nice quality Shirt',price:10},
    {name:'Jeans',category:"clothes",description:'Good, Jeans',price:15},
    {name:'T-shirt',category:"clothes",description:'Good, T-shirt',price:10},
    {name:'Scarf',category:"clothes",description:'Good, Scarf',price:20},
    {name:'Loafers',category:"shoes",description:'Good, Loafers',price:50},
    {name:'Sneakers',category:"shoes",description:'Good, Sneakers',price:90},
    {name:'sandals',category:"shoes",description:'Good, sandals',price:50},
    {name:'sports shoes',category:"shoes",description:'Good, sports shoes',price:50},

]